- Cargo.toml
> Publish version 0.1.0

- ffi/include/coupe.h
It was already the case from the rust side.
> ffi: specify const to i_th's return type

- tools/src/bin/apply-part/main.rs
- tools/src/bin/apply-weight/main.rs
- tools/src/bin/weight-gen/main.rs
- tools/src/lib.rs
- edges are now ignored,
- instead of taking elements that are of the same dimension of the mesh,
this takes the elements that have the highest dimension.
Also this makes weight-gen use the shared barycentre code (and thus
const generics).
Fixes #75
> tools: change element types taken into account

- .github/workflows/ci.yml
related to C-FEATURE from the Rust API guidelines
<https://rust-lang.github.io/api-guidelines/checklist.html>
See #176
> ci: lint for feature names

- Cargo.lock
- Cargo.toml
Although it's still used by sprs.
> Remove ndarray dependency

- ffi/include/coupe.h
- ffi/src/data.rs
- ffi/src/lib.rs
- src/algorithms/ckk.rs
For compatibility with C strings
> ffi: Add missing nul bytes in error strings

- Cargo.lock
- src/algorithms/vn/best.rs
- tools/Cargo.toml
- tools/README.md
- tools/src/bin/mesh-part.rs
- tools/src/bin/part-bench.rs
- tools/src/ittapi.rs
- tools/src/ittapi_stub.rs
- tools/src/lib.rs
and highlight them in intel tools like vtune
> tools: Use ittapi to wrap algorithms into tasks

- .gitignore
- Cargo.lock
- src/algorithms/vn/best.rs
- src/algorithms/vn/first.rs
- src/imbalance.rs
- tools/num-part/Cargo.toml
- tools/num-part/README.md
- tools/num-part/src/database/migration-000-init.sql
- tools/num-part/src/database/mod.rs
- tools/num-part/src/help_after.txt
- tools/num-part/src/main.rs
- tools/src/lib.rs
> finish num-part port

- src/algorithms/vn/best.rs
- src/algorithms/vn/first.rs
- tools/doc/mesh-part.1.scd
- tools/report/common.sh
- tools/src/lib.rs
also infer the `part_count` argument from the input partition.
> Add vnbest and vnfirst runs to the quality script

- src/topology.rs
*See individual commits for details.*
> Misc changes

- src/algorithms/vn/first.rs
*See individual commits for details.*
> vn/first: misc changes

- tools/src/metis.rs
- tools/src/scotch.rs
Edge weights are cast from floats to ints, hopefully this won't cause issues.
> tools: feed edge weights to metis and scotch

- tools/src/scotch.rs
> tools: fix wrong argument order in call

- tools/src/bin/part-info.rs
> part-info: don't crash on null total_weight

- src/algorithms/hilbert_curve.rs
Tried to implement the 1DPART function from multijagged paper. It mostly works imbalance-wise, though there might be some edge cases that need to be covered and off-by-one errors to be fixed, I'm not 100% sure about the split indices.
Closes #201
> hilbert: implement paper version of MJ's 1dPart()

- tools/src/bin/part-bench.rs
So that it's possible to run it with a limited amount of threads without too much context switches:
RAYON_NUM_THREADS=32 part-bench ...
> part-bench: also pin threads outside of efficiency benchmarks

- tools/doc/mesh-part.1.scd
- tools/src/bin/part-bench.rs
> part-bench: allow fine grained thread counts

- .github/workflows/rustdoc.yml
- README.md
- docs/build.sh
- docs/index.html
- docs/man.css
- tools/doc/mesh-dup.1.scd
- tools/doc/mesh-part.1.scd
- tools/doc/mesh-refine.1.scd
- tools/doc/mesh-reorder.1.scd
- tools/doc/mesh-svg.1.scd
- tools/doc/part-info.1.scd
- tools/doc/weight-gen.1.scd
> ci: upload a front page and man pages

- src/algorithms/hilbert_curve.rs
Previously, weighted_quantiles would modify "splits" in place. While no actual bug or imbalance violations have been observed, this caused "splits" and "part_weights" to go out of sync. Later iterations of the inner for loop would use the newer splits with the former values of part_weights.
The split update is not done in parallel, because the overhead of rayon becomes too costly with high core counts.
It seems that this version also scales a bit better than master's, maybe because the for loop has been replaced with a closure and leads to better behavior wrt. the instruction cache? We'll never know.
> weighted_quantiles: fix splits "tearing"

- tools/src/bin/part-info.rs
Cherry-picked from #259
- total weight of each criterion,
- number of parts,
- the smallest and largest parts,
- the number of empty parts.
> part-info: print more information

- tools/src/bin/part-info.rs
- uniform: communication weight is the number of criterion
- linear: communication weight is the sum of criteria
- sqrt: communication weight is the sum of criteria's sqrt
Closes #221
> part-info: use --edge-weights for the lambda cut

- Cargo.lock
- Cargo.toml
- benches/rcb_cartesian.rs
- src/cartesian/mod.rs
- src/cartesian/rcb.rs
- src/lib.rs
- src/main.rs
- src/rayon_utils/fold_chunks.rs
- src/rayon_utils/mod.rs
Run the benchmark with
```
cargo bench --bench rcb_cartesian -- [--sample-size 10]
```
Run the test program with
```
cargo run -- WIDTH HEIGHT [RCB_ITERS]
```
> rcb for cartesian meshes

- src/cartesian/mod.rs
- src/cartesian/rcb.rs
*See individual commits for details.*
> Bug fixes and perf improvements

- src/algorithms/recursive_bisection.rs
> rcb: remove stray eprintln

- src/cartesian/rcb.rs
so that weighted_median works with O(sqrt(n)) weights instead of O(n). This should reduce memory accesses and speed up the overall execution.
> cartesian/rcb: collect axis weights into a vec

- src/algorithms/hilbert_curve.rs
- src/average.rs
- src/lib.rs
*See individual commits for details*
> Hilbert curve fixes

- src/algorithms/arc_swap.rs
- src/algorithms/hilbert_curve.rs
- src/cartesian/mod.rs
*See individual commits for details.*
> Add some tests and another hilbert fix

- .github/workflows/docker-publish-nightly.yml
- .github/workflows/docker-publish.yml
- Cargo.lock
- Dockerfile
Mostly followed https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
> Fix docker

- Cargo.lock
- Cargo.toml
- tools/Cargo.toml
- tools/mesh-io/Cargo.toml
- tools/num-part/Cargo.toml
- tools/src/bin/apply-part.rs
- tools/src/bin/apply-weight.rs
- tools/src/bin/mesh-dup.rs
- tools/src/bin/mesh-part.rs
- tools/src/bin/mesh-points.rs
- tools/src/bin/mesh-refine.rs
- tools/src/bin/mesh-reorder.rs
- tools/src/bin/mesh-svg.rs
- tools/src/bin/part-bench.rs
- tools/src/bin/weight-gen.rs
vtkio still relies on a very old "nom".
> Upgrade dependencies
