- src/algorithms/fiduccia_mattheyses.rs
while fm will always be identity for partitions where all vertices are
in the same part, this 1/ avoids having to compute the number of parts
twice at the begining and 2/ ensures the part_weights array has the
correct length.
> fm: force part_count to be 2

- .gitignore
- Cargo.lock
- Cargo.toml
- README.md
- ffi/Cargo.toml
- ffi/Doxyfile
- ffi/Makefile
- ffi/README.md
- ffi/examples/kk_fm.c
- ffi/examples/rcb.c
- ffi/include/coupe.h
- ffi/src/data.rs
- ffi/src/lib.rs
So that coupe can be used from most languages, not just rust.
The C interface follows this pattern:
A `struct coupe_iter` opaque type can be constructed in several ways, to
allow the user to feed coupe elements in different ways.
For example, if the user has an array of weights, they can use:
struct coupe_iter *w = coupe_iter_array(weight_count, weights);
or if they don't want to use weights:
int one = 1;
struct coupe_iter *w = coupe_iter_constant(weight_count, &one);
(very idiomatic C!  unfortunately for these function to be "generic" the
second argument has to be a `void *`)
and if they have a complex data structure that can be indexed:
ComplexWeightCollection *coll = /* ... */
struct coupe_iter *w =
coupe_iter_fn(coll, weight_count, get_ith_weight);
Algorithms are implemented as …
> Add a C interface to coupe

- ffi/Cargo.toml
We want coupe-ffi to have a library named coupe, so that the generated
objects are libcoupe.{a,so}.  However, this makes `cargo doc` fail
because it conflicts with the rust lib.
Since the rust-side of the documentation is not important (there already
is a documented, doxygen-compatible header file), this commit disables
the documentation on this crate.
> ffi: do not document rust crate

- tools/report/efficiency
- tools/src/bin/part-bench/main.rs
1. replaced ':' with ';' to work well with metis and scotch algorithms
2. trim the mesh file name from the weight file name, so that
triangles;triangles.constant;rcb,1
becomes
triangles;constant;rcb,1
and `triangles;triangles;hilbert,2` becomes `triangles;hilbert,2`,
because benchmark names are limited to 64 bytes by criterion.
Closes #101
> part-bench: change benchmark name format

- Cargo.lock
While this has no impact for our use case, it should remove those
dependabot popups on github.
<https://github.com/crossbeam-rs/crossbeam/security/advisories/GHSA-qc84-gqf4-9926>
<https://groups.google.com/g/rustlang-security-announcements/c/NcNNL1Jq7Yw>
<https://github.com/rust-num/num-bigint/security/advisories/GHSA-v935-pqmr-g8v9>
> Cargo.lock: update some dep versions

- src/algorithms/hilbert_curve.rs
- src/algorithms/k_means.rs
- src/algorithms/recursive_bisection.rs
- src/algorithms/z_curve.rs
- src/geometry.rs
- src/lib.rs
- tools/src/bin/medit2svg.rs
Extracted from #153
Renamed `Aabb` (axis aligned bounding box) to just `BoundinxBox`
Also renamed `Mbr` to `OrientedBoundingBox` (instead of arbitrarily oriented bounding box). Let me know if you have a better name for this.
Aabb is used for rcb in #165 to keep track of the min/max of each coordinate
> geometry: rename Aabb and Mbr

- tools/report/common.sh
- tools/report/quality
Only coupe-tools binary are used actually.  This reduces the number of
dependencies to build.
> tools: don't build all crates for quality reports

- Cargo.lock
- tools/doc/mesh-dup.1.scd
- tools/mesh-io/Cargo.toml
- tools/mesh-io/src/medit/mod.rs
- tools/src/bin/mesh-dup.rs
Used to duplicate a mesh N times for finer-grained weak scaling
measurements.
In a future commit, it should be possible to connect the duplicates
together by mirroring half of them.
> tools: add a mesh duplication tool

- tools/report/efficiency-weak
- tools/report/weak-scaling
a little POSIX shell script that measures the weak scaling of an
algorithm with the help of part-bench, weight-gen and mesh-refine.
Example:
./tools/report/weak-scaling monkey.meshb spike,1000 -a random,2 -a fm,0.04
The shell script was easier to code, but the overhead might be worth removing: the mesh is read twice per iteration (once by weight-gen and once by part-bench) and it uses the filesystem to store intermediate results.
> tools: add a weak-scaling measurement tool

- ffi/src/data.rs
- src/algorithms/recursive_bisection.rs
This PR changes the "array of structs" data structure in RCB to a "struct of arrays" (one for the weights, one for part IDs, and one for each dimension) to provide efficient data transfers to the GPU (and also allow for SIMD processing)
TODO
> rcb: prerequisites for GPU acceleration

- src/algorithms.rs
- src/algorithms/ckk.rs
- src/algorithms/greedy.rs
- src/algorithms/hilbert_curve.rs
- src/algorithms/kk.rs
- src/algorithms/multi_jagged.rs
- src/algorithms/recursive_bisection.rs
- src/algorithms/vn/best.rs
- src/algorithms/vn/first.rs
- src/algorithms/z_curve.rs
- src/lib.rs
- tools/mesh-io/src/lib.rs
- tools/mesh-io/src/medit/parser.rs
- tools/mesh-io/src/weight.rs
related to C-METADATA from the Rust API guidelines
<https://rust-lang.github.io/api-guidelines/checklist.html>
This lint is specifically added to the rust libraries: coupe and
mesh-io.
See #176
> ci: lint for missing debug implementations

- src/algorithms.rs
- src/algorithms/ckk.rs
- src/algorithms/greedy.rs
- src/algorithms/hilbert_curve.rs
- src/algorithms/kk.rs
- src/algorithms/multi_jagged.rs
- src/algorithms/recursive_bisection.rs
- src/algorithms/vn/best.rs
- src/algorithms/vn/first.rs
- src/algorithms/z_curve.rs
- src/lib.rs
- tools/mesh-io/src/lib.rs
related to C-COMMON-TRAITS from the Rust API guidelines
<https://rust-lang.github.io/api-guidelines/checklist.html>
This lint is specifically added to the rust libraries: coupe and
mesh-io.
See #176
> ci: lint for missing Copy implementations

- Cargo.lock
- tools/Cargo.toml
- tools/src/bin/mesh-part/main.rs
- tools/src/bin/part-bench/main.rs
- tools/src/lib.rs
- tools/src/metis.rs
- tools/src/scotch.rs
Computing the dual takes some time and is not needed when all algorithms
are geometric.  This commit makes it so the dual (and barycentres, for
topologic/number runs) is only computed when necessary.
Somewhat related to #126
> tools: only compute dual and barycentres when needed

- Cargo.lock
- ffi/Cargo.toml
- ffi/src/data.rs
- ffi/src/lib.rs
- src/lib.rs
- tools/Cargo.toml
- tools/src/bin/medit2svg.rs
- tools/src/bin/mesh-part.rs
- tools/src/bin/part-info.rs
- tools/src/lib.rs
Namely nalgebra, num traits, rayon and sprs.
Those crates appear in coupe's public API (through function parameters
and trait bounds). Having reexports allows consumers of the library to
use it without adding extra dependencies in their package manifest.
> Reexport dependencies of coupe's public API

- ffi/src/data.rs
Fix clippy lint introduced in clippy 1.63.
> ffi: derive Eq

- src/topology.rs
- tools/doc/part-info.1.scd
- tools/report/quality
- tools/src/bin/part-info.rs
and other related changes, see individual commits for details.
It turns out reports showed incorrect edge cuts because part-info was not called with the same `--edge-weights` setting as mesh-part.
Closes #194
> part-info: add the -E,--edge-weights option 

- src/algorithms/arc_swap.rs
- tools/report/common.sh
This just makes arcswap consider all parts when making a move.
For each vertex to move, arcswap considers all the parts to move it to,
then picks the part that yields the greatest gain.
> arcswap: kway generalization

- tools/src/bin/part-info.rs
part-info would yield negative imbalances for perfectly balanced
partitions (e.g. with Karmarkar-Karp).
Related: #199
> part-info: ensure imbalances are positive

- Cargo.lock
- src/lib.rs
- tools/Cargo.toml
- tools/src/bin/weight-gen.rs
Previously, linear distribution was computed as
ALPHA = (to - from) / (max - min)
BETA  = -min * ALPHA
w_i = FMA(p_i, ALPHA, BETA) + from
(ie. (p_i-min) * (to-from)/(max-min)+from)
Now it is computed as such
ALPHA = (to - from) / (max - min)
w_i = FMA(p_i-min, ALPHA, from)
(ie. (p_i-min) * (to-from)/(max-min)+from)
This should do the trick:
- for the lower bound, if `p_i` is `min` then the FMA operation has 0.0 as first argument and thus should yield `from`;
- for the upper bound, this uses the same `nextafter` technique as the implementation of Hilbert curves, to work around float errors.
Closes #202
> weight-gen: enforce linear to be within bounds

- src/algorithms/arc_swap.rs
- tools/report/imbedgecut.sh
Now arcswap works in passes (bulk synchronous). Each pass does:
- copy the part weights
- threads make the moves
- aggregate the updated part weights from threads
- reduce to the updated global part weights (avoid having to compute the part weights from scratch)
... until a pass has no gain. This should fix the end conditions, albeit performance is yet to be measured.
This also changes the max_part_weight (thread-local maximum for the part weights) so that is accounts for all threads correctly.
This commit fixes the bipart violations, but 128-part tests show that it's not totally fixed.
Closes #197
> arcswap: fix imbalance violations

- tools/src/bin/weight-gen.rs
Change error display from `Some("...")` to `"..."`. Keep using the debug impl to print quotes around user input.
> weight-gen: fix axis error format

- .dockerignore
- .github/workflows/docker-publish-nightly.yml
- .github/workflows/docker-publish.yml
- Dockerfile
- tools/README.md
Summary :
- Dockerfile to build a minimal docker image containing coupe bins
- Add meshes exemples
- Add new github action (must be manually triggered)
Pros:
- Usefull for hands-on sessions / paper submissions
TODO:
> Add Dockerfile And Github Action Triggering Docker Push

- tools/doc/weight-gen.1.scd
- tools/src/bin/weight-gen.rs
For a 3D mesh, `weight-gen -d spike,HEIGHT,POS_x,POS_y,POS_z`. For a 2D mesh, `POS_z` must be omitted. Can have multiple spikes at the same time:
> weight-gen: allow multiple spikes

- tools/src/lib.rs
- tools/src/metis.rs
- tools/src/scotch.rs
These tools cannot handle null weights for vertices nor edges, so the input weights are "zoomed in" so that the sum of the weights plus one is INT_MAX.
Closes #220
> tools: scale and shift vertex and edge weights for METIS and SCOTCH

- tools/src/lib.rs
- tools/src/metis.rs
~~not tested yet.~~
We have to multiply the tolerance by 1000 and convert it to an int for METIS.
See <https://lihpc-computational-geometry.github.io/metis-rs/metis/option/struct.UFactor.html>
By default the tolerance for Recursive is 0.001 and for Kway 0.03
Closes #226
> tools: add a tolerance parameter for METIS

- tools/doc/apply-part.1.scd
- tools/doc/mesh-dup.1.scd
- tools/doc/mesh-part.1.scd
- tools/doc/mesh-refine.1.scd
- tools/doc/mesh-reorder.1.scd
- tools/doc/weight-gen.1.scd
- tools/src/bin/apply-part.rs
- tools/src/bin/apply-weight.rs
- tools/src/bin/medit2svg.rs
- tools/src/bin/mesh-dup.rs
- tools/src/bin/mesh-part.rs
- tools/src/bin/mesh-refine.rs
- tools/src/bin/mesh-reorder.rs
- tools/src/bin/weight-gen.rs
- tools/src/lib.rs
Both following invocations are now accepted:
weight-gen -d constant,1 mesh weights
weight-gen -d constant,1 <mesh >weights
To read from stdin and write to a file, you can use "-" (as most command-line utilities do):
weight-gen -d constant,1 - weights <mesh
Closes #229
> tools: accept free arguments in addition to stdin/out

- Cargo.lock
- tools/mesh-io/ffi/Cargo.toml
- tools/mesh-io/ffi/src/lib.rs
std defines std::ffi::c_int and std::os::raw::c_int, however the later module is marked as deprecated?
> meshio/ffi: use std's c_int instead of libc's

- tools/src/metis.rs
- tools/src/scotch.rs
not tested yet
The scaling/shifting is already done for integer weights, so might as well do it for floats.
Closes #232
> tools: add float weight support for METIS and SCOTCH

- tools/doc/apply-part.1.scd
- tools/doc/mesh-dup.1.scd
- tools/doc/mesh-refine.1.scd
- tools/doc/mesh-reorder.1.scd
- tools/src/bin/apply-part.rs
- tools/src/bin/apply-weight.rs
- tools/src/bin/mesh-dup.rs
- tools/src/bin/mesh-refine.rs
- tools/src/bin/mesh-reorder.rs
- tools/src/lib.rs
So the following invocations will produce a VTK ASCII file and a MEDIT binary file respectively:
apply-weight -m my_mesh.vtk -w weights.dat my_mesh_with_weights.vtk
mesh-refine my_mesh.vtk refined_mesh.meshb
> tools: infer mesh format from extension

- examples/simple.rs
- ffi/src/lib.rs
- src/algorithms/hilbert_curve.rs
- tools/src/lib.rs
The 3D implementation needs a smaller lookup table, because there is
twice as many configurations to go from an order to the next. Therefore,
the LUT allow for only 3 bit to be computed at a time (instead of 6).
Its layout is similar however, configurations are encoded on 3 bits
instead of 2.
To prevent trait implementation conflicts, HilbertCurve can only
implement Partition for &[PointND] instead of all P: AsRef<[_]>.
cube split in 5 equal parts
> hilbert: add a simple 3D implementation

- Cargo.toml
- src/algorithms/k_means.rs
- src/algorithms/recursive_bisection.rs
- src/lib.rs
- tools/src/lib.rs
This commit adds a SIMD variant for the partitioning step (splitting the array of coordinates into two).
Bramas, B. (2017) ‘A Novel Hybrid Quicksort Algorithm Vectorized using
AVX-512 on Intel Skylake’, International Journal of Advanced Computer
Science and Applications, 8(10). <doi:10.14569/IJACSA.2017.081044>.
^ the partitioning algorithm in this paper is the one used in google's highway project:
https://github.com/google/highway/blob/c25f7f568ddd61e51c3e93c74377558176e5d108/hwy/contrib/sort/vqsort-inl.h#L280
AVX512F, AVX512VL and rust nightly[^1] are required, check support on your machine with
rustc +nightly --print cfg -C target-cpu=native | grep -E 'avx512f|avx512vl'
This implementation uses `__m256` registers instead of `__m512` since coordinates are `f32` and part IDs (of type …
> rcb: SIMD partitioning

- src/algorithms/hilbert_curve.rs
Since it's using the 1DPART algorithm from said paper.
Cherry-picked from a local commit i made for #243
> hilbert: add ref to Multi-Jagged paper

- .github/workflows/ci.yml
The other clippy and test jobs also do a superset of cargo check, so this job is useless for us.
> ci: remove cargo check job

- .github/workflows/coverage.yml
<https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/>
Example warning:
https://github.com/LIHPC-Computational-Geometry/coupe/actions/runs/3541583767
> ci: update to codecov@v3 to fix github warning

- src/algorithms/arc_swap.rs
- src/algorithms/recursive_bisection.rs
- src/average.rs
- src/lib.rs
Otherwise there can be concurrent moves on neighbors V and U when:
1. Thread A computes the gain of V
2. Thread B computes the gain of U
3. Thread A locks V
4. Thread A checks for locks on neighbors of V
-> there are none because B didn't lock U yet
5. Thread A moves V and releases the lock
6. Thread B locks U
7. Thread B checks for locks on neighbors of U
-> there are none because A released the lock
8. Thread B moves U
> arcswap: lock vertex *before* gain calculations (and other things)

- ffi/src/lib.rs
- src/algorithms/hilbert_curve.rs
- tools/mesh-io/ffi/src/lib.rs
- tools/mesh-io/src/medit/parser.rs
- tools/src/bin/mesh-part.rs
You don't need to "use std::mem::drop;"...
> it seems drop is part of std::prelude?

- .github/workflows/docker-publish-nightly.yml
- .github/workflows/docker-publish.yml
- Dockerfile
Fix Dockerfile linter step in docker publish nightly workflow by adding ignore rules :
- DL3006: false positive due to the builder pattern used
- DL3008: afaik, we don't want to pin versions in apt get install
Other changes:
- avoid additional packages by specifying `--no-install-recommends` in Dockerfiler
- add Dockerfile linter step to manual build action
> CI: Fix docker linter step

- src/cartesian/mod.rs
- tools/num-part/src/database/mod.rs
- tools/src/bin/mesh-part.rs
- tools/src/bin/part-bench.rs
- tools/src/lib.rs
Since we start with coord=1, Grid::part_of must also be called with coord=1, otherwise the partition array ends up being transposed.
> cartesian: fix partition being transposed

- tools/README.md
- tools/doc/mesh-points.1.scd
- tools/src/bin/mesh-points.rs
- tools/src/bin/mesh-svg.rs
The `--with-ids` argument only works with medit meshes, at least until #288 is fixed.
> tools: add a mesh-points utility

- tools/build.rs
- tools/doc/apply-part.1.scd
- tools/doc/mesh-dup.1.scd
- tools/doc/mesh-part.1.scd
- tools/doc/mesh-refine.1.scd
- tools/doc/mesh-reorder.1.scd
- tools/doc/mesh-svg.1.scd
- tools/doc/part-info.1.scd
- tools/doc/weight-gen.1.scd
- tools/src/bin/apply-part.rs
- tools/src/bin/apply-weight.rs
- tools/src/bin/mesh-dup.rs
- tools/src/bin/mesh-part.rs
- tools/src/bin/mesh-refine.rs
- tools/src/bin/mesh-reorder.rs
- tools/src/bin/mesh-svg.rs
- tools/src/bin/part-bench.rs
- tools/src/bin/part-info.rs
- tools/src/bin/weight-gen.rs
and print help/version on stdout instead of stderr, at least when specifically requested with -h,--help, so that it's easier to pipe into other programs
> tools: add argument to show version

- tools/mesh-io/src/medit/parser.rs
Detect " MeshVersionFormatted" as medit, even though there is a space at the start
> meshio: skip whitespace for format detection

- src/algorithms/fiduccia_mattheyses.rs
The extensions could be implemented at some point.
Closes #304
> fm: remove mention of kway support in docs

- tools/Cargo.toml
- tools/README.md
- tools/src/bin/apply-part.rs
- tools/src/bin/apply-weight.rs
- tools/src/bin/mesh-dup.rs
- tools/src/bin/mesh-part.rs
- tools/src/bin/mesh-points.rs
- tools/src/bin/mesh-refine.rs
- tools/src/bin/mesh-reorder.rs
- tools/src/bin/mesh-svg.rs
- tools/src/bin/part-bench.rs
- tools/src/bin/part-info.rs
- tools/src/bin/weight-gen.rs
- tools/src/lib.rs
- tools/src/metis.rs
- tools/src/scotch.rs
- tools/src/zoom_in.rs
some quality of life improvements
- show enable cargo features on `bin --version` (useful to known when intel profiling support is enabled)
- disable scotch and metis by default (since they require clang)
- fix some dead code warnings when scotch and metis are disabled
> tool: fixes and improvements related to cargo features

- tools/src/metis.rs
- tools/src/scotch.rs
- tools/src/zoom_in.rs
The idea is that we have weights
- in some [min; max] range,
- whose sum is S
and we want to scale them so
1. they fit into some integer type,
2. the output sum is below INTMAX
3. the output has no zeroes
basically we apply an affine function "y=scale*x+offset" where scale and offset depend on the max output value M:
(M-1) * x + max - M*min
y = -------------------------
max - min
y=1 for x=min and y=M for x=max
M is set so that the sum of all "y" is INTMAX (N is the number of weights):
(max - min) * INTMAX + sum(x) - max * N
M = -----------------------------------------
sum(x) - min * N
> tools: fix integer scaling for metis/scotch
